"""feature_usage: scope the unique edge by symbol/timeframe, not just feature/consumer.

Found live (2026-07-16, Volume 3 DEBT-9 build): `feature_usage`'s only
unique constraint was `(feature_name, consumer)`, with `symbol`/`timeframe`
buried inside the JSONB `data` column instead of being real columns.
`FeatureSelectionEngine._persist_usage()`'s upsert targets exactly that
constraint, so recommending the same feature name (e.g. `price_alpha_50` --
a generic technical indicator every symbol can rank highly) for two
different symbols silently overwrites the first symbol's row instead of
recording both. Reproduced live before this migration: running selection
for 5 watchlist symbols x 10 recommended features each produced only 48
rows, not 50 -- 2 already lost to same-feature-name collisions across
symbols (HDFCBANK's `volume_mfi_50` and `price_alpha_50` rows were
clobbered by ICICIBANK's and TCS's respectively). Scheduling this engine
across the full 25-symbol watchlist without this fix would make most of
the table's content "whichever symbol ran last for that feature name" --
i.e. actively wrong, not just incomplete.

Adds real `symbol`/`timeframe` columns (matching `feature_quality`'s
existing pattern) and widens the unique edge to
`(feature_name, consumer, symbol, timeframe)`. The 48 rows already written
during this investigation are cleared, not backfilled -- they were
generated by exactly the bug this migration fixes and don't represent
valid recommendation history.

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-16

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute("TRUNCATE TABLE feature_usage")
    op.drop_constraint("uq_feature_usage_edge", "feature_usage", type_="unique")
    op.add_column(
        "feature_usage", sa.Column("symbol", sa.String(50), nullable=False, server_default="")
    )
    op.add_column(
        "feature_usage", sa.Column("timeframe", sa.String(10), nullable=False, server_default="")
    )
    op.alter_column("feature_usage", "symbol", server_default=None)
    op.alter_column("feature_usage", "timeframe", server_default=None)
    op.create_unique_constraint(
        "uq_feature_usage_edge",
        "feature_usage",
        ["feature_name", "consumer", "symbol", "timeframe"],
    )
    op.create_index(
        "ix_feature_usage_symbol_timeframe", "feature_usage", ["symbol", "timeframe"]
    )


def downgrade() -> None:
    op.drop_index("ix_feature_usage_symbol_timeframe", table_name="feature_usage")
    op.drop_constraint("uq_feature_usage_edge", "feature_usage", type_="unique")
    op.drop_column("feature_usage", "timeframe")
    op.drop_column("feature_usage", "symbol")
    op.create_unique_constraint(
        "uq_feature_usage_edge", "feature_usage", ["feature_name", "consumer"]
    )
